#! /usr/bin/perl

my ${dir} = "/mnt/".$ARGV[0]."/reports/";
my ${report_name} = "report.csv";
my ${report_path} = ${dir}.${report_name};

my ${linecount} = 0;
my ${fieldcount} = 0;

open (REPORT, ${report_path});
	@{report} = <REPORT>;
close (REPORT);

print "Backup report for ", $ARGV[0];
print "\n\n";


foreach (@{report}) {
	if (${linecount} < 4 ) { 
		sleep 0;
	}else{

	
		if ( $_ =~ /"/ ){
			$_ =~ s/^"//;
			$_ =~ s/"$//;
			@fields = split /","/, $_;
		}else{
			@fields = split /,/, $_;
		}
		print $_;
		if ( @{fields}[0] == "" ){
			@{fields}[0] = @{fields}[2];
		}
		if ( @{fields}[8] == "" ){
			@{fields}[8] = "None";
		}
		
#		print @{fields}[0], " started at ", @fields[5], "\n";
#		print "Status:\t\t", @fields[3], "\n";
#		print "Log messages:\n";
#		print "\t Date:\t\t", ${fields}[7], "\n";
#		print "\t Message:\t", ${fields}[8], "\n";
#		print "\t Time\t\t", ${fields}[9], "\n";
#		print "\n\n";
		print $linecount, "\n";
		foreach (@fields) {
		print $field;
		}

	}
	print "\n";
	${linecount}++
}
