#! /usr/bin/perl

use warnings;
use strict;

my $location = $ARGV[0];
my $from = $ARGV[1];
my $to = $ARGV[2];
my $searchterm = $ARGV[3];

my $searchdir="/mnt/".$location."/bad";
my $todaydir="/mnt/".$location."/in";


my $from_key;
my $to_key;
my @email;
my $date;
my @emails;
my $cmd;
my $grep;
my $this_date;

opendir (BAD, $searchdir) || die ("Error opening $searchdir");
	my @dates = readdir(BAD);
closedir(BAD);
#my @sorted_dates = sort(($a) <=> $b ), @dates;
my @sorted_dates = sort @dates;

my $count = 0;
foreach (@sorted_dates){
	if ( $_ =~ m/^\d/ ){
		if ( $_ >= $from && $_ <= $to ){
			## This is effectively a loop through the dirs from $from to $to
		
#			print $_, "\n";

			$this_date = $_;
			my $path = "/mnt/".$location."/bad/".$_;

			opendir (DATE, $path);
				@emails = readdir(DATE);
			closedir (DATE);

				foreach (@emails){
					$cmd = "grep -i ".$searchterm." ".$path."/".$_." | wc -l";
					$grep = qx/$cmd/;
#				print $grep, " ";
					if ($grep > 0){
#						print "<a href='".$path."/".$_."'>".$_."</a> \n"
						print $_;
						print "\t";
						print $this_date;
						print "\n";
					}

				}

		}
	}
}

print "\n"




	
