#! /usr/bin/perl
## ArcServe backup report processor
@locations=(london,scanachrome,glasgow);
$report_name = "report.csv";

foreach(@locations){

	print $_."\n";

	$dir = "/mnt/".$_."/reports/";
	$report_path = $dir.$report_name;
	$linecount = 0;
	$fieldcount = 0;

	if (-e $report_path){

		open(REPORT, $report_path) || print ("error opening $report_path");
			@report = <REPORT>;
			$modified_date = localtime( (stat REPORT)[9]);
		close(REPORT);
		
	#	print "\t".$modified_date."\n";
	
		foreach (@report) {
			if ($linecount < 4) { 
				sleep 0;
			}else{

				@fields = split /,/, $_;
				if ( $_ =~ /"/){
					@description = split(/\"/, $_);
					$description = @description[1];
				}else{
					$description = @fields[3];
				}
				chomp($description);

				if(@fields[1] =~ /Failed/i){
					@fields[1] = "**FAILED**";
				}else{
					@fields[1] = " ".@fields[1];
				}

				print "\t\t",@fields[1],"\t",$description,"\t\n";


			}	
			$linecount++
		
		}
		unlink $report_path;
	}else{
		print "\t*** No report found at $report_path ***\n";
	}

	print "\n";
}
