#! /usr/bin/perl

$in = $ARGV[0];
my $out;
$out="abc";

if (@ARGV!=1 && @ARGV!=2){
	print "Usage:\n\t$0 input-file [output-file]\n";
	exit 0;
}

open(IN, $in);
	while (<in>){
		chomp;
		chop;
		$_.="\n";
		$output.=$_;
	}
close (IN);

if (@ARGV==1){
	unlink $in;
	$out=$in;
}elsif (@ARGV==2){
	$out=$argv[1];

}
open(OUT, ">$out") or die "Can't open $out";
	print OUT $output;
close(OUT);

