#! /usr/bin/perl


my ${dir} = "/mnt/".$ARGV[0]."/reports/";
#my ${dir} = "/mnt/london/reports/";
#my ${dir} = "/home/avi/bin/perl/reports/";
my ${report_name} = "report.csv";
my ${archive} = "/mnt/london/reports/old";
my ${today} = qx/date +%y%m%d/;
my ${line_count} = 0;
my ${field_count} = 0;

#if ( $ARGV[1] != "" ){
#	my ${max_field_length} = $ARGV[1];
#}else{
	my ${max_field_length}=10;
#}

#if ( $ARGV[2] != "" ){
#	my ${min_field_length} = $ARGV[2];
#}else{
	my ${min_field_length}=8;
#}

my ${waste};
my ${short_field_name};

## Mail!
my ${sendmail} = "/usr/sbin/sendmail -t";
my ${to} = 'To: avi.greenbury@servicegraphics.co.uk';
my ${from} = 'From: backup-alert';
my ${subject} = 'Subject: Backup report for';
##

my ${report_path} = ${dir};
${report_path}.=${report_name};

open (REPORT, ${report_path} ) || die "Can't read report at ${report_path}";
	@{report} = <REPORT>;
close (REPORT);

#open (MAIL, "|${sendmail}") || die "Couldn't open ${sendmail}";
#print MAIL ${to}, "\n";
#print MAIL ${from}, "\n";
#print MAIL ${subject}, "\n";


	foreach (@{report}) {

		${cur_line} = $_;

		if (${line_count} < 3){
			
			print ${cur_line};
			${line_count}++;
		}elsif (${line_count} == 3 ){
			@{field_names} = split (/,/, ${cur_line});
			foreach (@{field_names}) {
				${cur_field_name} = $_;
				@{short_field_name}=split /\./, ${cur_field_name};
				if ( length(${short_field_name}[1]) > ${max_field_length} ) {
					${short_field_name}[1] = substr ${short_field_name}[1], 0, ${max_field_length};
				}elsif ( length( ${short_field_name}[1] ) < ${min_field_length}) {
					${short_field_name}[1].="\t";
				}
				print  ${short_field_name}[1];
				print "\t";
			}
			${line_count}++;
		} elsif (${line_count} > 3) {
			@{fields}=split (/,/, ${cur_line});
	
			foreach (@{fields}){
				${field} = $_;
				${field} =~ s/Database/db/;
				${field} =~ s/Exchange//;
#				${field} =~ s/caroot//;
				${field} =~ s/2008/08/;
	
				if ( length(${field}) > ${max_field_length}) {
					${field} = substr ${field}, 0, ${max_field_length};
				} elsif ( length(${field}) < ${min_field_length} ){
					${field}.="\t";
				}


				print ${field};
				print "\t  ";
				${line_count}++;
			}
#			print "\n";
		}
		print "\n";
	}
print "\n";
close;
