#! /usr/bin/perl

my @locations = ("london", "glasgow");
my $goodmail = "/var/goodmail/";
my $logname = "spamlog";

my $cmd = 'date -d yesterday +%y%m%d';
my $yesterday = qx/$cmd/;
chomp $yesterday;


foreach (@locations){
	$location = $_;
	
	my $total_time = 0;
	my $total_in = 0;
	my $total_good = 0;
	my $total_bad = 0;
	my $count = 0;

	print "\n", $location, "\n\n";

	$logfile_path = $goodmail.$location."/".$yesterday."/".$logname;

	open (LOGFILE, "$logfile_path") || die ("Couldn't open logfile at $logfile_path");
		foreach $line (<LOGFILE>){
			print "\t", $line;
			($time, $in, $good, $good_percent, $rate) = (split (/\s/, $line))[5,6,7,8,9];
			
			$time =~ s/s$//i;
			$in =~ s/^in://i;
			$good =~ s/^good://i;

			$good =~ s/^\s//i;
			$good =~ s/\s$//i;

			$total_in += $in;
			$total_time += $time;
			$total_good += $good;
			$count ++;
		}
	close (LOGFILE);

	$messages_per_second = $total_in / $total_time;
	$messages_per_second = sprintf("%.2f", $messages_per_second);

	print "\n\tTotals:\tTime:\t", $total_time;
	print "\n\t\t\tIn:\t", $total_in;
	print "\n\t\t\tGood:\t", $total_good;
	print "\n\tAverage messages per second: ", $messages_per_second;
	print "\n\n";
	
}

