#! /bin/bash
tempfile=/tmp/userdir

du -mc --summarize /mnt/london/users/* | sort -nr | sed s/\ /./ > $tempfile

while read line
do
	size=$(echo $line | awk '{ print $1 }' )
	gb=$(echo "scale=2; $size/1024" | bc)
	name=$(echo $line | awk '{ print $2 }' | awk -F/ '{ print $5 }')
	echo "${gb}GB	$name"
#echo $line
done < $tempfile


