#! /bin/bash

spamlog=/home/avi/bin/spamlog

while getopts "lmh" option
do
	case $option in
		m)	more $spamlog; exit;;
		l)	less $spamlog; exit;;
		v)	vim $spamlog; exit;;
		*)	cat $spamlog; exit;;
	esac
done

cat $spamlog

exit
