#! /usr/bin/perl

use strict;
use warnings;

#Needs to be one less than the first tape because of bad maths.
my ${tape_start} = 119;
#The first tape is ${tape_start} + 1. tape 0, therefore, doesn't exist IRL.

my ${weeks} = 2;

my ${today} = (localtime)[3];
my ${today_number} = (localtime)[6];

my @{days} = ("Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat");
my ${today_name} = ${days}[${today_number}];

my @{month_name}=("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec");
my ${this_month_number}=(localtime)[4];
my ${this_month_name}=${month_name}[${this_month_number}];

my @{month_length}=("31", "28", "31", "30", "31", "30", "31", "31", "30", "31", "30", "31");
my ${this_year} = (localtime)[5] + 1900;

## Detect leap years badly
## If four digit year divides by four but not 100, is leap.
if ( ${this_year} % 4 ) {
	sleep 0
}else{
	if ( ${this_year} % 100 ) {
		${month_length}[1] = "29";
	}
}


my ${this_month} = (localtime)[4];
my ${this_month_length}=${month_length}[${this_month}];

my ${today_tape} = ${tape_start} + ${today};


my ${next_monday} = ${today} + (8 - ${today_number} );
#my ${monday_after} = ${next_monday} + 7;

print "${today_name}", "\t", "${today_number}", "\t", "${today_tape}", "\n";

my ${day_number} = ${next_monday};

#print ${day_number};

#${weeks} = 10;
for ( 1 .. ${weeks} ){

	print "\n";

	for my $i ( 1 .. 5){

		if ( ${day_number} > ${this_month_length} ){
			${day_number} = ${day_number} - ${this_month_length}
		}


		my ${day_name} = ${days}[${i}];
		my ${tape_number} = ${tape_start} + ${day_number};

		if ( ${day_number} == ${this_month_length} ){
			print "${day_name}", "\t", "${day_number}", "\t", "${this_month_name}", " end", "\n";
			${this_month_number}++;
			${this_month_name}=${month_name}[${this_month_number}];
		}else{
			print "${day_name}", "\t", "${day_number}", "\t", "${tape_number}", "\n";
		}
		${day_number}++;
	}

	${day_number} = ${day_number} + 2 
}

print "\n";
