-- SQL behind machines-with-office-07-on-them report:

select MACHINE.NAME, SOFTWARE.DISPLAY_NAME

from (
	
	(
		(
			MACHINE_SOFTWARE_JT join MACHINE on
				MACHINE_SOFTWARE_JT.MACHINE_ID = MACHINE.ID
		) join (
			SOFTWARE
		) on MACHINE_SOFTWARE_JT.SOFTWARE_ID = SOFTWARE.ID
	
	) join (
		MACHINE_LABEL_JT join LABEL on
			MACHINE_LABEL_JT.LABEL_ID=LABEL.ID
	) on MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID
			
)

WHERE SOFTWARE.DISPLAY_NAME
REGEXP '^Microsoft Office[ ]*[a-z]*[ ]2007$'
