select *

from(
	(
		(	
			MACHINE_LABEL_JT join LABEL on
				MACHINE_LABEL_JT.LABEL_ID = LABEL.ID
		)join(
			MACHINE on MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID
		)
	)join(
		(
			MACHINE_SOFTWARE_JT join MACHINE on
				MACHINE_SOFTWARE_JT.MACHINE_ID = MACHINE.ID
		)join(
			SOFTWARE on MACHINE_SOFTWARE_JT.SOFTWARE_ID = SOFTWARE.ID
		)
	) on MACHINE_LABEL_JT.MACHINE_ID = MACHINE_SOFTWARE_JT.MACHINE_ID
)
